# Generated by Django 4.1.7 on 2023-04-25 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0004_alter_proyecto_fecha_inicio_and_more"),
        ("gastos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gastos",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="proyectos.proyecto",
            ),
        ),
    ]
