# Generated by Django 4.1.7 on 2023-04-26 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "trabajadores_proveedores",
            "0002_alter_trabajadoresproveedores_archivos_and_more",
        ),
        ("gastos", "0002_gastos_proyecto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gastos",
            name="cobrador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="trabajadores_proveedores.trabajadoresproveedores",
            ),
        ),
    ]
