# Generated by Django 4.1.3 on 2023-04-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGastos',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(blank=True, max_length=20, null=True)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=20, null=True)),
                ('cobrador', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_gastos',
            },
        ),
    ]
