# Generated by Django 4.1.3 on 2023-04-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajadoresProveedores',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=20, null=True)),
                ('concepto', models.CharField(blank=True, max_length=20, null=True)),
                ('archivos', models.CharField(blank=True, max_length=100, null=True)),
                ('contratos', models.CharField(blank=True, max_length=50, null=True)),
                ('monto_contrato', models.FloatField(blank=True, null=True)),
                ('abonos', models.FloatField(blank=True, null=True)),
                ('saldo', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trabajadores_proveedores',
            },
        ),
    ]
