# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 497)
        MainWindow.setMinimumSize(QtCore.QSize(700, 497))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidgetodo = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidgetodo.sizePolicy().hasHeightForWidth())
        self.centralwidgetodo.setSizePolicy(sizePolicy)
        self.centralwidgetodo.setAutoFillBackground(False)
        self.centralwidgetodo.setStyleSheet("background-color: rgb(240, 241, 245);")
        self.centralwidgetodo.setObjectName("centralwidgetodo")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidgetodo)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.framenavbar = QtWidgets.QFrame(self.centralwidgetodo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framenavbar.sizePolicy().hasHeightForWidth())
        self.framenavbar.setSizePolicy(sizePolicy)
        self.framenavbar.setMinimumSize(QtCore.QSize(0, 0))
        self.framenavbar.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"\n"
"}")
        self.framenavbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framenavbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framenavbar.setLineWidth(0)
        self.framenavbar.setObjectName("framenavbar")
        self.gridLayout = QtWidgets.QGridLayout(self.framenavbar)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_7 = QtWidgets.QPushButton(self.framenavbar)
        self.pushButton_7.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("public/rectangle1650@3x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.framenavbar)
        self.framelineasuperior = QtWidgets.QFrame(self.centralwidgetodo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framelineasuperior.sizePolicy().hasHeightForWidth())
        self.framelineasuperior.setSizePolicy(sizePolicy)
        self.framelineasuperior.setMinimumSize(QtCore.QSize(0, 0))
        self.framelineasuperior.setStyleSheet("  background-color: transparent;")
        self.framelineasuperior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framelineasuperior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framelineasuperior.setObjectName("framelineasuperior")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.framelineasuperior)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.framelineasuperior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setStyleSheet("background-image: url(\"public/vector-lineashorizontales3.svg\");  \n"
"background-repeat: repeat-x;\n"
"background-position: center;")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.verticalLayout_4.addWidget(self.framelineasuperior)
        self.framebtnsuperior = QtWidgets.QFrame(self.centralwidgetodo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framebtnsuperior.sizePolicy().hasHeightForWidth())
        self.framebtnsuperior.setSizePolicy(sizePolicy)
        self.framebtnsuperior.setMinimumSize(QtCore.QSize(0, 0))
        self.framebtnsuperior.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.framebtnsuperior.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.framebtnsuperior.setStyleSheet("  background-color: transparent;\n"
"")
        self.framebtnsuperior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framebtnsuperior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framebtnsuperior.setObjectName("framebtnsuperior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.framebtnsuperior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.framebtnsuperior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(206, 0))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setAccessibleName("")
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("  cursor: pointer;\n"
"  border: 0;\n"
"  padding: 0;\n"
"  background-color: transparent;\n"
"  position: absolute;\n"
"  top: 171px;\n"
"  left: 37px;\n"
"  width: 424.5px;\n"
"  height: 292px;\n"
"\n"
"  position: absolute;\n"
"  height: 100%;\n"
"  width: 100%;\n"
"  top: 0;\n"
"  right: 0;\n"
"  bottom: 0;\n"
"  left: 0;")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("public/btnproyectos.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(206, 141))
        self.pushButton.setAutoExclusive(True)
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label_15 = QtWidgets.QLabel(self.framebtnsuperior)
        self.label_15.setStyleSheet("position: absolute;\n"
"background-color: transparent;\n"
"background-image: url(\"public/vector-lineashorizontales3.svg\");  \n"
"background-repeat: repeat-x;\n"
"background-position: center;\n"
"transform: rotate(90deg);\n"
"height:;\n"
"")
        self.label_15.setText("")
        self.label_15.setScaledContents(False)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)
        self.pushButton_6 = QtWidgets.QPushButton(self.framebtnsuperior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(206, 0))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setAccessibleName("")
        self.pushButton_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_6.setAutoFillBackground(False)
        self.pushButton_6.setStyleSheet("  cursor: pointer;\n"
"  border: 0;\n"
"  padding: 0;\n"
"  background-color: transparent;\n"
"  position: absolute;\n"
"  top: 171px;\n"
"  left: 37px;\n"
"  width: 424.5px;\n"
"  height: 292px;\n"
"\n"
"  position: absolute;\n"
"  height: 100%;\n"
"  width: 100%;\n"
"  top: 0;\n"
"  right: 0;\n"
"  bottom: 0;\n"
"  left: 0;")
        self.pushButton_6.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("public/btngastos.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon2)
        self.pushButton_6.setIconSize(QtCore.QSize(206, 141))
        self.pushButton_6.setAutoExclusive(True)
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.label_16 = QtWidgets.QLabel(self.framebtnsuperior)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout.addWidget(self.label_16)
        self.pushButton_2 = QtWidgets.QPushButton(self.framebtnsuperior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(206, 0))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setAccessibleName("")
        self.pushButton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("  cursor: pointer;\n"
"  border: 0;\n"
"  padding: 0;\n"
"  background-color: transparent;\n"
"  position: absolute;\n"
"  top: 171px;\n"
"  left: 37px;\n"
"  width: 424.5px;\n"
"  height: 292px;\n"
"\n"
"  position: absolute;\n"
"  height: 100%;\n"
"  width: 100%;\n"
"  top: 0;\n"
"  right: 0;\n"
"  bottom: 0;\n"
"  left: 0;")
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("public/btnprospecto.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(206, 141))
        self.pushButton_2.setAutoExclusive(True)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_4.addWidget(self.framebtnsuperior)
        self.framecentro = QtWidgets.QFrame(self.centralwidgetodo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framecentro.sizePolicy().hasHeightForWidth())
        self.framecentro.setSizePolicy(sizePolicy)
        self.framecentro.setMinimumSize(QtCore.QSize(0, 0))
        self.framecentro.setStyleSheet(" background-color: transparent;\n"
"")
        self.framecentro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framecentro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framecentro.setObjectName("framecentro")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.framecentro)
        self.horizontalLayout_2.setContentsMargins(12, 0, 12, 0)
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.framecentro)
        self.label_9.setMinimumSize(QtCore.QSize(0, 0))
        self.label_9.setStyleSheet("position: absolute;\n"
"background-color: transparent;\n"
"background-image: url(\"public/vector-lineashorizontales3.svg\");  \n"
"background-repeat: repeat-x;\n"
"background-position: center;\n"
"height:;")
        self.label_9.setText("")
        self.label_9.setScaledContents(False)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.label_12 = QtWidgets.QLabel(self.framecentro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(100, 100))
        self.label_12.setStyleSheet(" position: absolute; /* se necesita para ajustar las dimensiones */\n"
"  top: 0;\n"
"  left: 0;\n"
"  right: 0;\n"
"  bottom: 0;\n"
"background-color: transparent;\n"
"  width: 100%; /* se establece un ancho del 100% para ocupar todo el contenedor */\n"
"  height: 100%; /* se establece una altura del 100% para ocupar todo el contenedor */\n"
"  min-width: 70px; /* se establece un ancho mínimo */\n"
"  min-height: 67px; /* se establece una altura mínima en función de la relación de aspecto (70:67) */\n"
"  aspect-ratio: 70/67; /* se establece la relación de aspecto del objeto */\n"
"")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("public/circulo-centro.svg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.label_10 = QtWidgets.QLabel(self.framecentro)
        self.label_10.setStyleSheet("position: absolute;\n"
"background-color: transparent;\n"
"background-image: url(\"public/vector-lineashorizontales3.svg\");  \n"
"background-repeat: repeat-x;\n"
"background-position: center;\n"
"height:;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.label_13 = QtWidgets.QLabel(self.framecentro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(100, 100))
        self.label_13.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_13.setStyleSheet(" position: absolute; /* se necesita para ajustar las dimensiones */\n"
"  top: 0;\n"
"  left: 0;\n"
"  right: 0;\n"
"  bottom: 0;\n"
"background-color: transparent;\n"
"  width: 100%; /* se establece un ancho del 100% para ocupar todo el contenedor */\n"
"  height: 100%; /* se establece una altura del 100% para ocupar todo el contenedor */\n"
"  min-width: 70px; /* se establece un ancho mínimo */\n"
"  min-height: 67px; /* se establece una altura mínima en función de la relación de aspecto (70:67) */\n"
"  aspect-ratio: 70/67; /* se establece la relación de aspecto del objeto */\n"
"")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("public/circulo-centro.svg"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.label_8 = QtWidgets.QLabel(self.framecentro)
        self.label_8.setStyleSheet("position: absolute;\n"
"background-color: transparent;\n"
"background-image: url(\"public/vector-lineashorizontales3.svg\");  \n"
"background-repeat: repeat-x;\n"
"background-position: center;\n"
"height:;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.horizontalLayout_2.setStretch(0, 20)
        self.horizontalLayout_2.setStretch(1, 13)
        self.horizontalLayout_2.setStretch(2, 14)
        self.horizontalLayout_2.setStretch(3, 13)
        self.horizontalLayout_2.setStretch(4, 20)
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_8.raise_()
        self.label_13.raise_()
        self.label_12.raise_()
        self.verticalLayout_4.addWidget(self.framecentro)
        self.framebtninferior = QtWidgets.QFrame(self.centralwidgetodo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framebtninferior.sizePolicy().hasHeightForWidth())
        self.framebtninferior.setSizePolicy(sizePolicy)
        self.framebtninferior.setMinimumSize(QtCore.QSize(0, 0))
        self.framebtninferior.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.framebtninferior.setStyleSheet("  background-color: transparent;")
        self.framebtninferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framebtninferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framebtninferior.setObjectName("framebtninferior")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.framebtninferior)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.framebtninferior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setAccessibleName("")
        self.pushButton_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_5.setAutoFillBackground(False)
        self.pushButton_5.setStyleSheet("  cursor: pointer;\n"
"  border: 0;\n"
"  padding: 0;\n"
"  background-color: transparent;\n"
"  position: absolute;\n"
"  top: 171px;\n"
"  left: 37px;\n"
"  width: 424.5px;\n"
"  height: 292px;\n"
"\n"
"  position: absolute;\n"
"  height: 100%;\n"
"  width: 100%;\n"
"  top: 0;\n"
"  right: 0;\n"
"  bottom: 0;\n"
"  left: 0;")
        self.pushButton_5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("public/btntrabajadores.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(206, 141))
        self.pushButton_5.setAutoExclusive(True)
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.label_17 = QtWidgets.QLabel(self.framebtninferior)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.pushButton_3 = QtWidgets.QPushButton(self.framebtninferior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setAccessibleName("")
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("  cursor: pointer;\n"
"  border: 0;\n"
"  padding: 0;\n"
"  background-color: transparent;\n"
"  position: absolute;\n"
"  top: 171px;\n"
"  left: 37px;\n"
"  width: 424.5px;\n"
"  height: 292px;\n"
"\n"
"  position: absolute;\n"
"  height: 100%;\n"
"  width: 100%;\n"
"  top: 0;\n"
"  right: 0;\n"
"  bottom: 0;\n"
"  left: 0;")
        self.pushButton_3.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("public/btnmateriales.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon5)
        self.pushButton_3.setIconSize(QtCore.QSize(206, 141))
        self.pushButton_3.setAutoExclusive(True)
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.label_18 = QtWidgets.QLabel(self.framebtninferior)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.pushButton_4 = QtWidgets.QPushButton(self.framebtninferior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setAccessibleName("")
        self.pushButton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setStyleSheet("  cursor: pointer;\n"
"  border: 0;\n"
"  padding: 0;\n"
"  background-color: transparent;\n"
"  position: absolute;\n"
"  top: 171px;\n"
"  left: 37px;\n"
"  width: 424.5px;\n"
"  height: 292px;\n"
"\n"
"  position: absolute;\n"
"  height: 100%;\n"
"  width: 100%;\n"
"  top: 0;\n"
"  right: 0;\n"
"  bottom: 0;\n"
"  left: 0;")
        self.pushButton_4.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("public/btnclientes.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon6)
        self.pushButton_4.setIconSize(QtCore.QSize(206, 141))
        self.pushButton_4.setAutoExclusive(True)
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.horizontalLayout_4.setStretch(0, 3)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 3)
        self.horizontalLayout_4.setStretch(3, 1)
        self.horizontalLayout_4.setStretch(4, 3)
        self.verticalLayout_4.addWidget(self.framebtninferior)
        self.framelineainferior = QtWidgets.QFrame(self.centralwidgetodo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framelineainferior.sizePolicy().hasHeightForWidth())
        self.framelineainferior.setSizePolicy(sizePolicy)
        self.framelineainferior.setMinimumSize(QtCore.QSize(0, 0))
        self.framelineainferior.setStyleSheet("  background-color: transparent;")
        self.framelineainferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framelineainferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framelineainferior.setObjectName("framelineainferior")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.framelineainferior)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.framelineainferior)
        self.label_6.setMinimumSize(QtCore.QSize(700, 0))
        self.label_6.setStyleSheet("background-image: url(\"public/vector-lineashorizontales3.svg\");  \n"
"background-repeat: repeat-x;\n"
"background-position: center;")
        self.label_6.setText("")
        self.label_6.setScaledContents(False)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.verticalLayout_4.addWidget(self.framelineainferior)
        self.framefooter = QtWidgets.QFrame(self.centralwidgetodo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framefooter.sizePolicy().hasHeightForWidth())
        self.framefooter.setSizePolicy(sizePolicy)
        self.framefooter.setMinimumSize(QtCore.QSize(0, 0))
        self.framefooter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framefooter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framefooter.setObjectName("framefooter")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.framefooter)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.framefooter)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setStyleSheet("background-color: transparent;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("public/vector-esquinainferiorizquierda.svg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.framefooter)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setStyleSheet("background-image: url(public/vector-lineainferiorizquierda.svg);\n"
"\n"
"\n"
"background-color: transparent;")
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.framefooter)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setStyleSheet("background-color: transparent;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("public/vector-centroinferior.svg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.framefooter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setStyleSheet("background-color: transparent;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("public/vector-lineainferiorderecha.svg"))
        self.label_4.setScaledContents(False)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.framefooter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setStyleSheet("background-color: transparent;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("public/vector-esquinainferiorderecha.svg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_3.setStretch(0, 3)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 3)
        self.horizontalLayout_3.setStretch(3, 2)
        self.horizontalLayout_3.setStretch(4, 3)
        self.verticalLayout_4.addWidget(self.framefooter)
        self.verticalLayout_4.setStretch(0, 2)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 5)
        self.verticalLayout_4.setStretch(3, 2)
        self.verticalLayout_4.setStretch(4, 5)
        self.verticalLayout_4.setStretch(5, 1)
        self.verticalLayout_4.setStretch(6, 2)
        self.framebtnsuperior.raise_()
        self.framefooter.raise_()
        self.framenavbar.raise_()
        self.framelineainferior.raise_()
        self.framelineasuperior.raise_()
        self.framebtninferior.raise_()
        self.framecentro.raise_()
        MainWindow.setCentralWidget(self.centralwidgetodo)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
