-- Table: public.project_proveedores_trabajadores

-- DROP TABLE IF EXISTS public.project_proveedores_trabajadores;

CREATE TABLE IF NOT EXISTS public.project_proveedores_trabajadores
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(50) COLLATE pg_catalog."default",
    telefono bigint,
    correo character varying(50) COLLATE pg_catalog."default",
    direccion character varying(50) COLLATE pg_catalog."default",
    especialidad character varying(20) COLLATE pg_catalog."default",
    concepto character varying(20) COLLATE pg_catalog."default",
    archivos character varying(100) COLLATE pg_catalog."default",
    contratos character varying(50) COLLATE pg_catalog."default",
    monto_contrato double precision,
    abonos double precision,
    saldo double precision,
    CONSTRAINT project_proveedores_trabajadores_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.project_proveedores_trabajadores
    OWNER to postgres;