# Generated by Django 4.1.7 on 2023-02-23 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adco_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectproveedorestrabajadores',
            table='project_proveedores_trabajadores',
        ),
    ]
