# Generated by Django 4.1.7 on 2023-02-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adco_crud', '0002_alter_projectproveedorestrabajadores_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproveedorestrabajadores',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
