# Generated by Django 4.1.7 on 2023-02-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adco_crud', '0003_alter_projectproveedorestrabajadores_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproveedorestrabajadores',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
