# Generated by Django 4.1.7 on 2023-04-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prospectos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prospectos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=15)),
                ("observaciones", models.TextField()),
            ],
        ),
        migrations.DeleteModel(name="TrabajadoresProveedores",),
    ]
