# Generated by Django 4.1.3 on 2023-04-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectClientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('documentos', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'project_clientes',
            },
        ),
    ]
