# Generated by Django 4.1.7 on 2023-04-07 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proyecto", models.CharField(max_length=50)),
                ("institucion_empresa", models.CharField(max_length=50)),
                ("fecha_inicio", models.DateField(auto_now=True)),
                ("fecha_termino", models.DateField(auto_now=True)),
                ("telefono", models.BigIntegerField(max_length=10)),
                ("direccion", models.CharField(max_length=50)),
                ("ubicacion", models.CharField(max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "proyectos",},
        ),
    ]
