# Generated by Django 4.1.7 on 2023-04-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0002_alter_proyecto_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto", name="telefono", field=models.IntegerField(),
        ),
    ]
