# Generated by Django 4.1.7 on 2023-04-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0003_alter_proyecto_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto", name="fecha_inicio", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="proyecto", name="fecha_termino", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="telefono",
            field=models.CharField(max_length=10),
        ),
    ]
