# Generated by Django 4.1.7 on 2023-03-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materiales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="materiales",
            name="cantidad",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="materiales", name="concepto", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="materiales",
            name="fecha",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="materiales",
            name="recurso",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
