# Generated by Django 4.1.7 on 2023-03-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materiales", "0002_materiales_cantidad_materiales_concepto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recursos",
            name="nombre",
            field=models.CharField(default="nombre_recurso", max_length=50),
        ),
        migrations.AddField(
            model_name="recursos", name="precio", field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="recursos",
            name="tipo",
            field=models.CharField(default="estructural", max_length=50),
        ),
    ]
