# Generated by Django 4.1.7 on 2023-04-26 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("materiales", "0004_materiales_proyecto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materiales",
            name="recurso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materiales.recursos",
            ),
        ),
    ]
