# Generated by Django 4.1.7 on 2023-04-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materiales", "0005_alter_materiales_recurso"),
    ]

    operations = [
        migrations.RemoveField(model_name="recursos", name="created_by",),
        migrations.AddField(
            model_name="recursos",
            name="marca",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="recursos",
            name="unidad",
            field=models.CharField(default="Kilogramos", max_length=50),
        ),
    ]
