# Generated by Django 4.1.7 on 2023-04-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materiales", "0006_remove_recursos_created_by_recursos_marca_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="materiales", name="total", field=models.FloatField(default=0.0),
        ),
    ]
