# Generated by Django 4.1.7 on 2023-03-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("contrasena", models.CharField(max_length=30)),
                ("edad", models.IntegerField()),
                ("posicion", models.CharField(max_length=30)),
                ("telefono", models.CharField(max_length=10)),
            ],
            options={"db_table": "usuarios",},
        ),
    ]
