# Generated by Django 4.1.7 on 2023-03-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("metodo_pago", models.CharField(max_length=50)),
                ("fecha", models.DateField(auto_now=True)),
                ("documentos", models.CharField(max_length=70)),
                ("observaciones", models.CharField(max_length=100)),
            ],
            options={"db_table": "clientes",},
        ),
    ]
