# Generated by Django 4.1.7 on 2023-03-27 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0002_clientes_created_by_alter_clientes_documentos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientes",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="documentos",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="clientes", name="fecha", field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="clientes", name="nombre", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="clientes",
            name="observaciones",
            field=models.TextField(blank=True),
        ),
    ]
