# Generated by Django 4.1.7 on 2023-04-25 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0004_alter_proyecto_fecha_inicio_and_more"),
        (
            "clients",
            "0003_alter_clientes_created_by_alter_clientes_documentos_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="clientes",
            name="proyecto_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="proyectos.proyecto",
            ),
        ),
    ]
