# Generated by Django 4.1.7 on 2023-04-26 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("prospectos", "0003_prospectos_created_by"),
        ("clients", "0005_rename_proyecto_id_clientes_proyecto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientes",
            name="nombre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="prospectos.prospectos"
            ),
        ),
    ]
