# Generated by Django 4.1.7 on 2023-04-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectos',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
