# Generated by Django 4.1.7 on 2023-02-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_api', '0004_updated_createdAt_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notemodel',
            options={'ordering': ['-createdAt']},
        ),
    ]
