# Generated by Django 4.1.7 on 2023-04-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
