# Generated by Django 4.1.7 on 2023-04-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_proyectos_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='id_proyecto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
