# Generated by Django 4.1.7 on 2023-04-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trabajadores_proveedores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trabajadoresproveedores",
            name="archivos",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="trabajadoresproveedores",
            name="contratos",
            field=models.TextField(),
        ),
    ]
