# Generated by Django 4.1.3 on 2023-04-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaterials',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('recurso', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('concepto', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_materials',
            },
        ),
    ]
