# Generated by Django 4.1.3 on 2023-04-12 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_clientes', '0001_initial'),
        ('project_materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmaterials',
            name='id_proyecto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='project_clientes.projectclientes'),
        ),
    ]
